### ISSUE TITLE
Issue with yahooquery/fc.yahoo.com causing theprivateinvestor not to work

### ISSUE THREAD

**Issue by niko-ger** [JerBouma/ThePassiveInvestor#10]
Hi Jeroen,

There seems to be a problem with yahooquery/fc.yahoo.com that causes various applications, including your package thepassiveinvestor, to be unable to retrieve information for any ticker.

More details here: [YahooQueryIssue](https://github.com/dpguthrie/yahooquery/issues/241)

I personally kept getting the following error in the beginning:
**ConnectionError: HTTPSConnectionPool(host= fc.yahoo.com , port=443): Max retries exceeded with url: / (Caused by ReadTimeoutError( HTTPSConnectionPool(host= fc.yahoo.com , port=443): Read timed out. (read timeout=5) ))**

And then I tried to follow some of the suggested solutions (I am based in Europe/Germany) but none worked for me.
I also tried with different versions of yahooquery (the one I got when installing your package was 2.3.3, but what the posts recommended were more recent ones - 2.3.5 or 2.3.7 - but also none of those worked).

Now I am getting from thepassiveinvestor package this error: see the attached pic.
<img width="923" alt="code_error" src="https://github.com/JerBouma/ThePassiveInvestor/assets/155118987/7b302b34-8c44-4186-831c-72fd562f6e3d">

I was wondering if you have an idea how this can be fixed.
Thanks in advance.

Kind regards,
Niko

**Comment by JerBouma** [comment]
Hi Niko, I am going to have a look if I can make the package a bit more robust. Unfortunately, the reliance on Yahoo Finance makes this package a bit unstable. Perhaps give the [Finance Toolkit](https://github.com/JerBouma/FinanceToolkit) a shot to see if it fits your needs? It also accepts ETFs.

**Comment by JerBouma** [comment]
Fixed the issue, it unfortunately will always be a bit unstable.

<img width="793" alt="image" src="https://github.com/JerBouma/ThePassiveInvestor/assets/46355364/03a6e256-0056-407f-9b9e-7a342ba52447">
