### ISSUE TITLE
It works not properly on Mac OS

### ISSUE THREAD

**Issue by SnowyThinker** [JerBouma/ThePassiveInvestor#4]
![image](https://user-images.githubusercontent.com/4386778/74840184-8108eb80-5361-11ea-911f-b4c3df631626.png)

It doesn't works properly on Mac OS, My network condition is good.

Python: 3.6

OS version: macOS 10.14.6 (18G87)

**Comment by JerBouma** [comment]
Few suggestions:
- Can you try including the drive? (i.e. `C:/Users/andrew/Desktop/ThePassiveInvestor.xlsx'`)
- Try a different Tickers URL
- Create an Excel file that includes a few tickers (if this works, then it has something to do with the URL)

Unfortunately I do not own a Mac so I can not adequately reproduce the error. Please let me know if it works.

**Comment by SnowyThinker** [comment]
Thank you JerBouma.

It works well after added 'time.sleep(3)' in report.py. I thought yahoo finance block the request after massive requests.


~~~python
for ticker in tickers:
    time.sleep(3)
    progress = Label(self, text="Creating report for " + ticker,bg=buttonColor,fg=buttonTextColour)
    progress.grid(row=4,column=1, columnspan=2, sticky=W+E+N+S,padx=10, pady=10)
~~~

**Comment by JerBouma** [comment]
Hmm, alright. In case this issue pops up more frequently I will include it in the base code!
