### ISSUE TITLE
Error: Not able to collect data for V00

### ISSUE THREAD

**Issue by AlonsoFU** [JerBouma/ThePassiveInvestor#9]
Hi! 

While running the code, with the required libraries, send me this error:

"Not able to collect data for V00"

The code is just the one in the description: 

import thepassiveinvestor as pi

# Collect data from a specific ETF
vanguard_sp500 = pi.collect_data('V00')

Much thanks in advance

**Comment by JerBouma** [comment]
Seems to be an issue from YahooFinance, also see: https://github.com/ranaroussi/yfinance/issues/1729. Unfortunately we will have to wait until this issue is resolved.

**Comment by AlonsoFU** [comment]
Thanks for the response :) !

**Comment by JerBouma** [comment]
This should be resolved, note that you wrote `V00` while it should be `VOO` instead:

<img width="554" alt="image" src="https://github.com/JerBouma/ThePassiveInvestor/assets/46355364/4b41018d-1093-4166-9d9e-cfe4fc6683c6">
